server:
  address: 127.0.0.1
#???
spring:
  application:
    name: passport
  cloud:
    nacos:
      discovery:
        server-addr: ${server.nacos}:8848
        enabled: true
      config:
        server-addr: ${server.nacos}:8848

